apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricrolebinding
subjects:
  - kind: ServiceAccount
    name: hello
    namespace: sprinkler8
roleRef:
  kind: ClusterRole
  name: metricrole
  apiGroup: rbac.authorization.k8s.io